apiVersion: apps/v1
kind: Deployment
metadata:
  name: becon-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: becon-bot
      tier: bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: becon-bot
        tier: bot
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: env
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env
        image: geekbeacon/beacon-bot:latest
        name: becon-bot
        volumeMounts:
        - mountPath: /app/config.js
          name: bot-config
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: bot-config
        configMap:
            name: bot-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  config.js: |
    {
    "token" : "BOT_TOKEN",
    "prefix" : "PREFIX_CHARACTER",

    "admin_role": "ADMINISTRATOR_ROLE_NAME",
    "super_role": "SUPER_MODERATOR_ROLE_NAME",
    "mod_role": "MODERATOR_ROLE_NAME",

    "admin_channel": "ADMINISTRATOR_CHANNEL_NAME",
    "super_channel": "SUPER_MODERATOR_CHANNEL_NAME",
    "mod_channel": "MODERATOR_CHANNEL_NAME",
    "super_log_channel": "SUPER_MODERATOR_LOG_CHANNEL_NAME",
    "action_log_channel": "MODERATOR_LOG_CHANNEL_NAME",

    "db_name" : "DATABASE_NAME",
    "db_host" : "DATABASE_HOST",
    "db_port" : 1234,
    "db_user" : "DATABASE_USER_NAME",
    "db_pass" : "DATABASE_PASSWORD"
}